# Generated by Django 3.1.4 on 2020-12-04 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('buying_price_tax_free', models.FloatField(default=0)),
                ('buying_price_full_tax', models.FloatField(default=0)),
                ('supplier_foreign_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stock_management.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='Zodd.jpg', upload_to='media/')),
                ('barcode', models.CharField(default='01234567891011', max_length=13)),
                ('capacity_volume', models.FloatField(default=0, max_length=100, verbose_name='Volume')),
                ('physical_unit', models.CharField(choices=[('KG', 'kilogramme'), ('L', 'Litre'), ('U', 'Unitaire')], default='L', max_length=100)),
                ('article_category', models.CharField(choices=[('alimentaire refrigere', 'alimentaire sec'), ('alimentaire sec', 'alimentaire refrigeres'), ('Non alimentaire', 'Non alimentaire')], default='Non alimentaire', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('composition', models.TextField(blank=True, default='')),
                ('is_active_selling', models.BooleanField(default=True)),
                ('selling_gross_price', models.FloatField(default=0, max_length=10000)),
                ('selling_conditions', models.FloatField(default=0, max_length=10000)),
                ('selling_net_price', models.FloatField(default=0, max_length=10000)),
                ('value_added_tax_rate', models.FloatField(choices=[(0.055, '5.5'), (0.1, '10'), (0.2, '20')], default='20')),
                ('value_added_tax_actual_value', models.FloatField(default=0, max_length=10000)),
                ('supplier_discount_percentage', models.FloatField(default=0, max_length=10000)),
                ('reference_supplier', models.CharField(default='1111111111111', max_length=13)),
                ('buying_price_tax_free', models.FloatField(default=0)),
                ('buying_conditions', models.FloatField(default=0)),
                ('is_active_buying', models.BooleanField(default=True)),
                ('current_stock', models.FloatField(default=0)),
                ('supplier_foreign_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stock_management.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.produit')),
            ],
        ),
        migrations.CreateModel(
            name='MergedOrder',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('order', models.ManyToManyField(related_name='orders', to='stock_management.Order')),
            ],
        ),
    ]
