# Generated by Django 3.1.6 on 2021-03-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='buying_conditions',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='buying_price_tax_free',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='capacity_volume',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='is_active_buying',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='is_active_selling',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='physical_unit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='reference_supplier',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='selling_conditions',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='selling_gross_price',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='supplier_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='value_added_tax_actual_value',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='value_added_tax_rate',
        ),
    ]
